use std::time::Duration;

use dbx_core::db::postgres;
use dbx_core::models::connection::DatabaseType;
use dbx_core::table_structure_sql::{
    build_table_structure_change_sql, EditableStructureIndex, TableStructureSqlOptions,
};

fn live_postgres_url() -> String {
    let host = std::env::var("DBX_LIVE_POSTGRES_HOST").unwrap_or_else(|_| "127.0.0.1".to_string());
    let port = std::env::var("DBX_LIVE_POSTGRES_PORT").ok().and_then(|value| value.parse().ok()).unwrap_or(5432);
    let user = std::env::var("DBX_LIVE_POSTGRES_USER").unwrap_or_else(|_| "postgres".to_string());
    let password = std::env::var("DBX_LIVE_POSTGRES_PASSWORD").unwrap_or_default();
    let database = std::env::var("DBX_LIVE_POSTGRES_DATABASE").unwrap_or_else(|_| "postgres".to_string());
    format!("postgresql://{user}:{password}@{host}:{port}/{database}")
}

fn concurrent_index(columns: Vec<&str>) -> EditableStructureIndex {
    EditableStructureIndex {
        id: "idx_users_email".to_string(),
        name: "idx_users_email".to_string(),
        columns: columns.into_iter().map(str::to_string).collect(),
        is_unique: false,
        is_primary: false,
        filter: String::new(),
        index_type: String::new(),
        included_columns: Vec::new(),
        comment: String::new(),
        concurrently: true,
        original: None,
        marked_for_drop: false,
    }
}

/// `CREATE INDEX CONCURRENTLY` generated by the table structure editor must
/// succeed on a real PostgreSQL server and leave a valid index
/// (`pg_index.indisvalid = true`).
#[tokio::test]
#[ignore = "requires DBX_LIVE_POSTGRES_HOST/PORT/USER/PASSWORD/DATABASE pointing at a writable PostgreSQL database"]
async fn live_postgres_concurrent_index_builds_valid_index() {
    let pool = postgres::connect(&live_postgres_url(), Duration::from_secs(10)).await.expect("connect PostgreSQL");
    let suffix = uuid::Uuid::new_v4().simple().to_string();
    let schema = format!("dbx_cic_{}", &suffix[..8]);
    let cleanup = vec![format!("DROP SCHEMA IF EXISTS \"{schema}\" CASCADE")];
    let _ = postgres::execute_batch(&pool, &cleanup).await;
    let setup = vec![
        format!("CREATE SCHEMA \"{schema}\""),
        format!("CREATE TABLE \"{schema}\".users (id integer PRIMARY KEY, email text, name text, status text)"),
    ];
    postgres::execute_batch(&pool, &setup).await.expect("create live test schema");

    let result = build_table_structure_change_sql(TableStructureSqlOptions {
        database_type: Some(DatabaseType::Postgres),
        schema: Some(schema.clone()),
        table_name: "users".to_string(),
        columns: Vec::new(),
        indexes: vec![concurrent_index(vec!["email"])],
        foreign_keys: Vec::new(),
        triggers: Vec::new(),
        table_comment: None,
        original_table_comment: None,
    });
    assert!(result.warnings.is_empty(), "{:?}", result.warnings);
    assert_eq!(
        result.statements,
        vec![format!("CREATE INDEX CONCURRENTLY \"idx_users_email\" ON \"{schema}\".\"users\" (\"email\");")]
    );

    postgres::execute_batch(&pool, &result.statements).await.expect("execute concurrent index build");
    let client = pool.get().await.expect("checkout connection");
    let row = client
        .query_one(
            "SELECT indisvalid FROM pg_index WHERE indexrelid = to_regclass($1)",
            &[&format!("{schema}.idx_users_email")],
        )
        .await
        .expect("read pg_index");
    let valid: bool = row.get(0);
    assert!(valid, "concurrently-built index must be valid");

    postgres::execute_batch(&pool, &cleanup).await.expect("cleanup live test schema");
}

/// PostgreSQL forbids `CREATE INDEX CONCURRENTLY` inside an explicit
/// transaction block; the editor relies on per-statement autocommit, so the
/// generated statement must only ever run outside `BEGIN`.
#[tokio::test]
#[ignore = "requires DBX_LIVE_POSTGRES_HOST/PORT/USER/PASSWORD/DATABASE pointing at a writable PostgreSQL database"]
async fn live_postgres_concurrent_index_rejects_transaction_block() {
    let pool = postgres::connect(&live_postgres_url(), Duration::from_secs(10)).await.expect("connect PostgreSQL");
    let suffix = uuid::Uuid::new_v4().simple().to_string();
    let schema = format!("dbx_cic_{}", &suffix[..8]);
    let cleanup = vec![format!("DROP SCHEMA IF EXISTS \"{schema}\" CASCADE")];
    let _ = postgres::execute_batch(&pool, &cleanup).await;
    let setup = vec![
        format!("CREATE SCHEMA \"{schema}\""),
        format!("CREATE TABLE \"{schema}\".users (id integer PRIMARY KEY, email text)"),
    ];
    postgres::execute_batch(&pool, &setup).await.expect("create live test schema");

    let client = pool.get().await.expect("checkout connection");
    client.batch_execute("BEGIN").await.expect("begin transaction");
    let err = client
        .batch_execute(&format!("CREATE INDEX CONCURRENTLY \"idx_users_email\" ON \"{schema}\".\"users\" (\"email\")"))
        .await
        .expect_err("CREATE INDEX CONCURRENTLY must fail inside a transaction block");
    let _ = client.batch_execute("ROLLBACK").await;
    let message = err.as_db_error().map(|db_error| db_error.message().to_string()).unwrap_or_else(|| err.to_string());
    assert!(
        message.contains("cannot run inside a transaction block"),
        "expected transaction-block error, got: {message}"
    );

    postgres::execute_batch(&pool, &cleanup).await.expect("cleanup live test schema");
}
